# Docker Compose configuration
version: '3.8'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
    depends_on:
      - zookeeper

  mongo:
    image: mongo
    ports:
      - "27017:27017"

  api:
    build:
      context: .
      dockerfile: deployment/Dockerfile.api
    ports:
      - "8000:8000"
    depends_on:
      - mongo

  dashboard:
    build:
      context: .
      dockerfile: deployment/Dockerfile.dashboard
    ports:
      - "8501:8501"
    depends_on:
      - mongo
